import { useState } from 'react';
import { ChevronDown, Mail, MapPin, Phone } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import type { Settings } from '@jad-home/shared';
import { api } from '../services/api';
import { useSeo } from '../hooks/useSeo';

const content: Record<string,{eyebrow:string;title:string;intro:string;sections:{title:string;body:string}[]}>= {
  about:{eyebrow:'Notre maison',title:'À propos de JAD HOME',intro:'Créer des intérieurs chaleureux, durables et profondément personnels.',sections:[{title:'Notre vision',body:'JAD HOME est une maison marocaine dédiée au mobilier, à la tapisserie et à la décoration. Nous réunissons des lignes contemporaines, des matières agréables à vivre et un service de proximité.'},{title:'Le goût du détail',body:'Chaque sélection cherche le juste équilibre entre confort, proportions et caractère. Les informations commerciales de ce site sont des exemples et restent modifiables depuis le dashboard.'},{title:'À vos côtés',body:'Notre équipe vous accompagne dans le choix des dimensions, des couleurs et des matières, jusqu’à la confirmation de la livraison.'}]},
  delivery:{eyebrow:'Bien recevoir',title:'Livraison',intro:'Une livraison organisée avec soin, partout au Maroc.',sections:[{title:'Zones desservies',body:'Nous livrons dans les principales villes du Maroc. La disponibilité et le délai précis sont confirmés sur WhatsApp avant validation.'},{title:'Délais',body:'Le délai dépend du stock, de la ville et du volume de la commande. Les produits sur mesure peuvent demander un délai complémentaire.'},{title:'Réception',body:'Vérifiez l’état des colis en présence du transporteur et signalez toute anomalie immédiatement.'}]},
  returns:{eyebrow:'Votre sérénité',title:'Retours & remboursements',intro:'Nous traitons chaque demande avec attention et transparence.',sections:[{title:'Signaler un problème',body:'Contactez-nous sous 48 heures après la livraison, avec votre référence de commande et des photos claires.'},{title:'Conditions',body:'Les articles doivent être inutilisés et conservés dans leur emballage. Les pièces personnalisées ou sur mesure ne sont généralement pas reprises.'},{title:'Traitement',body:'Après vérification, notre équipe vous communique la solution applicable : échange, réparation ou remboursement selon la situation.'}]},
  terms:{eyebrow:'Cadre de vente',title:'Conditions générales',intro:'Conditions de démonstration à faire valider avant mise en production.',sections:[{title:'Commande',body:'La commande est préremplie puis envoyée volontairement par le client dans WhatsApp. Elle devient définitive après confirmation de JAD HOME.'},{title:'Prix',body:'Les prix sont affichés en dirhams marocains. Le coût de livraison est confirmé avant validation finale.'},{title:'Disponibilité',body:'Le stock affiché est vérifié au moment de la commande. En cas d’indisponibilité, aucune obligation de vente ne peut être imposée.'}]},
  privacy:{eyebrow:'Vos données',title:'Politique de confidentialité',intro:'Nous limitons la collecte aux informations nécessaires à votre demande.',sections:[{title:'Données collectées',body:'Le formulaire de commande utilise les coordonnées que vous saisissez pour préparer un message WhatsApp. Elles ne sont pas enregistrées dans le catalogue Excel.'},{title:'Stockage local',body:'Le panier et la langue sont conservés dans le navigateur via localStorage. Vous pouvez les effacer à tout moment.'},{title:'Vos droits',body:'Contactez JAD HOME pour toute question relative à vos données personnelles.'}]},
};

export function InfoPage({type}:{type:keyof typeof content}){const page=content[type];useSeo(page.title,page.intro);return <><section className="bg-cream/60"><div className="container-page py-14 sm:py-20"><p className="eyebrow">{page.eyebrow}</p><h1 className="display-title max-w-4xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">{page.intro}</p></div></section><div className="container-page grid gap-8 py-14 sm:py-20 lg:grid-cols-3">{page.sections.map((section)=><section className="border-t border-charcoal pt-6" key={section.title}><h2 className="font-display text-3xl font-semibold">{section.title}</h2><p className="mt-4 text-sm leading-7 text-muted">{section.body}</p></section>)}</div></>}

const faq=[['Comment passer commande ?','Ajoutez vos articles au panier, remplissez vos coordonnées puis ouvrez le message prérempli dans WhatsApp. Vous devrez appuyer vous-même sur « Envoyer ».'],['Puis-je payer à la livraison ?','Oui, le paiement à la livraison est prévu dans cette première version, sous réserve de confirmation selon votre ville et votre commande.'],['Les prix sont-ils à jour ?','Le panier vérifie les prix et le stock auprès de l’API avant de préparer la commande.'],['Puis-je choisir une autre couleur ?','Les couleurs disponibles sont indiquées sur chaque fiche. Contactez-nous pour les possibilités de personnalisation.'],['Livrez-vous partout au Maroc ?','Nous couvrons les principales villes du Maroc. Le délai et le tarif sont confirmés avant validation.']];
export function FaqPage(){useSeo('Questions fréquentes','Réponses aux questions fréquentes sur JAD HOME.');return <div className="container-page max-w-4xl py-14 sm:py-20"><p className="eyebrow">Besoin d’aide ?</p><h1 className="display-title">Questions fréquentes</h1><div className="mt-10 divide-y divide-line border-y border-line">{faq.map(([q,a])=><FaqItem key={q} q={q} a={a}/>)}</div></div>}
function FaqItem({q,a}:{q:string;a:string}){const[open,setOpen]=useState(false);return <div><button className="flex min-h-16 w-full items-center justify-between gap-4 py-3 text-left font-semibold" onClick={()=>setOpen(!open)} aria-expanded={open}>{q}<ChevronDown className={`shrink-0 transition ${open?'rotate-180':''}`}/></button>{open&&<p className="pb-6 text-sm leading-7 text-muted">{a}</p>}</div>}

export function ContactPage(){useSeo('Contact','Coordonnées BELGA WOOD à configurer.');const settings=useQuery({queryKey:['settings'],queryFn:()=>api<Settings>('/api/settings/public')});return <div className="container-page py-14 sm:py-20"><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Parlons de votre intérieur</p><h1 className="display-title">Nous contacter</h1><p className="mt-6 max-w-lg leading-7 text-muted">Les nouvelles coordonnées BELGA WOOD seront ajoutées avant la mise en ligne.</p><div className="mt-9 space-y-4">{settings.data?.phone_number&&<ContactLine Icon={Phone} label="Téléphone" value={settings.data.phone_number}/>} {settings.data?.email&&<ContactLine Icon={Mail} label="Email" value={settings.data.email}/>} {settings.data?.address&&<ContactLine Icon={MapPin} label="Adresse" value={settings.data.address}/>}</div></div></div></div>}
function ContactLine({Icon,label,value}:{Icon:typeof Phone;label:string;value:string}){return <div className="flex items-start gap-4"><span className="grid size-11 place-items-center bg-cream"><Icon size={20}/></span><div><p className="text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div></div>}

export function NotFoundPage(){useSeo('Page introuvable','La page demandée est introuvable.');return <div className="container-page grid min-h-[60vh] place-items-center py-20 text-center"><div><p className="font-display text-8xl font-semibold text-gold">404</p><h1 className="section-title mt-2">Cette pièce n’est pas dans la collection.</h1><a href="/" className="btn-primary mt-8">Retour à l’accueil</a></div></div>}
